/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BergamoRouteImport } from './routes/bergamo'
import { Route as LaboratorioRouteImport } from './routes/laboratorio'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicComoFuncionaRouteImport } from './routes/_public.como-funciona'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as PublicInfluencersIndexRouteImport } from './routes/_public.influencers.index'
import { Route as PublicInfluencersSlugRouteImport } from './routes/_public.influencers.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BergamoRoute = BergamoRouteImport.update({
  id: '/bergamo',
  path: '/bergamo',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratorioRoute = LaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicComoFuncionaRoute = PublicComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const PublicInfluencersIndexRoute = PublicInfluencersIndexRouteImport.update({
  id: '/influencers/',
  path: '/influencers/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInfluencersSlugRoute = PublicInfluencersSlugRouteImport.update({
  id: '/influencers/$slug',
  path: '/influencers/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bergamo': typeof BergamoRoute
  '/laboratorio': typeof LaboratorioRoute
  '/como-funciona': typeof PublicComoFuncionaRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/': typeof AdminIndexRoute
  '/influencers/$slug': typeof PublicInfluencersSlugRoute
  '/influencers/': typeof PublicInfluencersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/bergamo': typeof BergamoRoute
  '/laboratorio': typeof LaboratorioRoute
  '/como-funciona': typeof PublicComoFuncionaRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/influencers/$slug': typeof PublicInfluencersSlugRoute
  '/influencers': typeof PublicInfluencersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bergamo': typeof BergamoRoute
  '/laboratorio': typeof LaboratorioRoute
  '/_public/como-funciona': typeof PublicComoFuncionaRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/influencers/$slug': typeof PublicInfluencersSlugRoute
  '/_public/influencers/': typeof PublicInfluencersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bergamo'
    | '/laboratorio'
    | '/como-funciona'
    | '/admin/auditoria'
    | '/admin/'
    | '/influencers/$slug'
    | '/influencers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/bergamo'
    | '/laboratorio'
    | '/como-funciona'
    | '/admin/auditoria'
    | '/'
    | '/admin'
    | '/influencers/$slug'
    | '/influencers'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/bergamo'
    | '/laboratorio'
    | '/_public/como-funciona'
    | '/admin/auditoria'
    | '/_public/'
    | '/admin/'
    | '/_public/influencers/$slug'
    | '/_public/influencers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BergamoRoute: typeof BergamoRoute
  LaboratorioRoute: typeof LaboratorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bergamo': {
      id: '/bergamo'
      path: '/bergamo'
      fullPath: '/bergamo'
      preLoaderRoute: typeof BergamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio': {
      id: '/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof LaboratorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/como-funciona': {
      id: '/_public/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof PublicComoFuncionaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/influencers/': {
      id: '/_public/influencers/'
      path: '/influencers'
      fullPath: '/influencers/'
      preLoaderRoute: typeof PublicInfluencersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/influencers/$slug': {
      id: '/_public/influencers/$slug'
      path: '/influencers/$slug'
      fullPath: '/influencers/$slug'
      preLoaderRoute: typeof PublicInfluencersSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicComoFuncionaRoute: typeof PublicComoFuncionaRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInfluencersSlugRoute: typeof PublicInfluencersSlugRoute
  PublicInfluencersIndexRoute: typeof PublicInfluencersIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicComoFuncionaRoute: PublicComoFuncionaRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicInfluencersSlugRoute: PublicInfluencersSlugRoute,
  PublicInfluencersIndexRoute: PublicInfluencersIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BergamoRoute: BergamoRoute,
  LaboratorioRoute: LaboratorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
