/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BergamoRouteImport } from './routes/bergamo'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LaboratorioRouteImport } from './routes/laboratorio'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicComoFuncionaRouteImport } from './routes/_public.como-funciona'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminBergamoRouteImport } from './routes/admin.bergamo'
import { Route as AdminBergamoUsuariosRouteImport } from './routes/admin.bergamo-usuarios'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminOfertasRouteImport } from './routes/admin.ofertas'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthInviteRouteImport } from './routes/auth.invite'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as CoprodutorBergamoRouteImport } from './routes/coprodutor.bergamo'
import { Route as MembrosIndexRouteImport } from './routes/membros.index'
import { Route as MembrosBergamoRouteImport } from './routes/membros.bergamo'
import { Route as PublicInfluencersIndexRouteImport } from './routes/_public.influencers.index'
import { Route as PublicInfluencersSlugRouteImport } from './routes/_public.influencers.$slug'
import { Route as ApiPublicDiagnosticsClientErrorRouteImport } from './routes/api/public/diagnostics.client-error'
import { Route as ApiPublicWebhooksHotmartRouteImport } from './routes/api/public/webhooks/hotmart'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BergamoRoute = BergamoRouteImport.update({
  id: '/bergamo',
  path: '/bergamo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratorioRoute = LaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicComoFuncionaRoute = PublicComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBergamoRoute = AdminBergamoRouteImport.update({
  id: '/bergamo',
  path: '/bergamo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBergamoUsuariosRoute = AdminBergamoUsuariosRouteImport.update({
  id: '/bergamo-usuarios',
  path: '/bergamo-usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfertasRoute = AdminOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const CoprodutorBergamoRoute = CoprodutorBergamoRouteImport.update({
  id: '/coprodutor/bergamo',
  path: '/coprodutor/bergamo',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosIndexRoute = MembrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembrosRoute,
} as any)
const MembrosBergamoRoute = MembrosBergamoRouteImport.update({
  id: '/bergamo',
  path: '/bergamo',
  getParentRoute: () => MembrosRoute,
} as any)
const PublicInfluencersIndexRoute = PublicInfluencersIndexRouteImport.update({
  id: '/influencers/',
  path: '/influencers/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInfluencersSlugRoute = PublicInfluencersSlugRouteImport.update({
  id: '/influencers/$slug',
  path: '/influencers/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const ApiPublicDiagnosticsClientErrorRoute =
  ApiPublicDiagnosticsClientErrorRouteImport.update({
    id: '/api/public/diagnostics/client-error',
    path: '/api/public/diagnostics/client-error',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksHotmartRoute =
  ApiPublicWebhooksHotmartRouteImport.update({
    id: '/api/public/webhooks/hotmart',
    path: '/api/public/webhooks/hotmart',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bergamo': typeof BergamoRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/laboratorio': typeof LaboratorioRoute
  '/membros': typeof MembrosRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/como-funciona': typeof PublicComoFuncionaRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/bergamo': typeof AdminBergamoRoute
  '/admin/bergamo-usuarios': typeof AdminBergamoUsuariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/coprodutor/bergamo': typeof CoprodutorBergamoRoute
  '/membros/bergamo': typeof MembrosBergamoRoute
  '/admin/': typeof AdminIndexRoute
  '/membros/': typeof MembrosIndexRoute
  '/influencers/$slug': typeof PublicInfluencersSlugRoute
  '/influencers/': typeof PublicInfluencersIndexRoute
  '/api/public/diagnostics/client-error': typeof ApiPublicDiagnosticsClientErrorRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/bergamo': typeof BergamoRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/laboratorio': typeof LaboratorioRoute
  '/prompts': typeof PromptsRoute
  '/como-funciona': typeof PublicComoFuncionaRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/bergamo': typeof AdminBergamoRoute
  '/admin/bergamo-usuarios': typeof AdminBergamoUsuariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/coprodutor/bergamo': typeof CoprodutorBergamoRoute
  '/membros/bergamo': typeof MembrosBergamoRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/membros': typeof MembrosIndexRoute
  '/influencers/$slug': typeof PublicInfluencersSlugRoute
  '/influencers': typeof PublicInfluencersIndexRoute
  '/api/public/diagnostics/client-error': typeof ApiPublicDiagnosticsClientErrorRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bergamo': typeof BergamoRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/laboratorio': typeof LaboratorioRoute
  '/membros': typeof MembrosRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/_public/como-funciona': typeof PublicComoFuncionaRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/bergamo': typeof AdminBergamoRoute
  '/admin/bergamo-usuarios': typeof AdminBergamoUsuariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/coprodutor/bergamo': typeof CoprodutorBergamoRoute
  '/membros/bergamo': typeof MembrosBergamoRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/membros/': typeof MembrosIndexRoute
  '/_public/influencers/$slug': typeof PublicInfluencersSlugRoute
  '/_public/influencers/': typeof PublicInfluencersIndexRoute
  '/api/public/diagnostics/client-error': typeof ApiPublicDiagnosticsClientErrorRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bergamo'
    | '/entrar'
    | '/equipe'
    | '/laboratorio'
    | '/membros'
    | '/prompts'
    | '/como-funciona'
    | '/admin/auditoria'
    | '/admin/bergamo'
    | '/admin/bergamo-usuarios'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/integracoes'
    | '/admin/ofertas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/auth/callback'
    | '/auth/invite'
    | '/auth/set-password'
    | '/coprodutor/bergamo'
    | '/membros/bergamo'
    | '/admin/'
    | '/membros/'
    | '/influencers/$slug'
    | '/influencers/'
    | '/api/public/diagnostics/client-error'
    | '/api/public/webhooks/hotmart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/bergamo'
    | '/entrar'
    | '/equipe'
    | '/laboratorio'
    | '/prompts'
    | '/como-funciona'
    | '/admin/auditoria'
    | '/admin/bergamo'
    | '/admin/bergamo-usuarios'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/integracoes'
    | '/admin/ofertas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/auth/callback'
    | '/auth/invite'
    | '/auth/set-password'
    | '/coprodutor/bergamo'
    | '/membros/bergamo'
    | '/'
    | '/admin'
    | '/membros'
    | '/influencers/$slug'
    | '/influencers'
    | '/api/public/diagnostics/client-error'
    | '/api/public/webhooks/hotmart'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/bergamo'
    | '/entrar'
    | '/equipe'
    | '/laboratorio'
    | '/membros'
    | '/prompts'
    | '/_public/como-funciona'
    | '/admin/auditoria'
    | '/admin/bergamo'
    | '/admin/bergamo-usuarios'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/integracoes'
    | '/admin/ofertas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/auth/callback'
    | '/auth/invite'
    | '/auth/set-password'
    | '/coprodutor/bergamo'
    | '/membros/bergamo'
    | '/_public/'
    | '/admin/'
    | '/membros/'
    | '/_public/influencers/$slug'
    | '/_public/influencers/'
    | '/api/public/diagnostics/client-error'
    | '/api/public/webhooks/hotmart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BergamoRoute: typeof BergamoRoute
  EntrarRoute: typeof EntrarRoute
  EquipeRoute: typeof EquipeRoute
  LaboratorioRoute: typeof LaboratorioRoute
  MembrosRoute: typeof MembrosRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  CoprodutorBergamoRoute: typeof CoprodutorBergamoRoute
  ApiPublicDiagnosticsClientErrorRoute: typeof ApiPublicDiagnosticsClientErrorRoute
  ApiPublicWebhooksHotmartRoute: typeof ApiPublicWebhooksHotmartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bergamo': {
      id: '/bergamo'
      path: '/bergamo'
      fullPath: '/bergamo'
      preLoaderRoute: typeof BergamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio': {
      id: '/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof LaboratorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/como-funciona': {
      id: '/_public/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof PublicComoFuncionaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bergamo': {
      id: '/admin/bergamo'
      path: '/bergamo'
      fullPath: '/admin/bergamo'
      preLoaderRoute: typeof AdminBergamoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bergamo-usuarios': {
      id: '/admin/bergamo-usuarios'
      path: '/bergamo-usuarios'
      fullPath: '/admin/bergamo-usuarios'
      preLoaderRoute: typeof AdminBergamoUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ofertas': {
      id: '/admin/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AdminOfertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/coprodutor/bergamo': {
      id: '/coprodutor/bergamo'
      path: '/coprodutor/bergamo'
      fullPath: '/coprodutor/bergamo'
      preLoaderRoute: typeof CoprodutorBergamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/': {
      id: '/membros/'
      path: '/'
      fullPath: '/membros/'
      preLoaderRoute: typeof MembrosIndexRouteImport
      parentRoute: typeof MembrosRoute
    }
    '/membros/bergamo': {
      id: '/membros/bergamo'
      path: '/bergamo'
      fullPath: '/membros/bergamo'
      preLoaderRoute: typeof MembrosBergamoRouteImport
      parentRoute: typeof MembrosRoute
    }
    '/_public/influencers/': {
      id: '/_public/influencers/'
      path: '/influencers'
      fullPath: '/influencers/'
      preLoaderRoute: typeof PublicInfluencersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/influencers/$slug': {
      id: '/_public/influencers/$slug'
      path: '/influencers/$slug'
      fullPath: '/influencers/$slug'
      preLoaderRoute: typeof PublicInfluencersSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/public/diagnostics/client-error': {
      id: '/api/public/diagnostics/client-error'
      path: '/api/public/diagnostics/client-error'
      fullPath: '/api/public/diagnostics/client-error'
      preLoaderRoute: typeof ApiPublicDiagnosticsClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/hotmart': {
      id: '/api/public/webhooks/hotmart'
      path: '/api/public/webhooks/hotmart'
      fullPath: '/api/public/webhooks/hotmart'
      preLoaderRoute: typeof ApiPublicWebhooksHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicComoFuncionaRoute: typeof PublicComoFuncionaRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInfluencersSlugRoute: typeof PublicInfluencersSlugRoute
  PublicInfluencersIndexRoute: typeof PublicInfluencersIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicComoFuncionaRoute: PublicComoFuncionaRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicInfluencersSlugRoute: PublicInfluencersSlugRoute,
  PublicInfluencersIndexRoute: PublicInfluencersIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminBergamoRoute: typeof AdminBergamoRoute
  AdminBergamoUsuariosRoute: typeof AdminBergamoUsuariosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminOfertasRoute: typeof AdminOfertasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminBergamoRoute: AdminBergamoRoute,
  AdminBergamoUsuariosRoute: AdminBergamoUsuariosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminOfertasRoute: AdminOfertasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MembrosRouteChildren {
  MembrosBergamoRoute: typeof MembrosBergamoRoute
  MembrosIndexRoute: typeof MembrosIndexRoute
}

const MembrosRouteChildren: MembrosRouteChildren = {
  MembrosBergamoRoute: MembrosBergamoRoute,
  MembrosIndexRoute: MembrosIndexRoute,
}

const MembrosRouteWithChildren =
  MembrosRoute._addFileChildren(MembrosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BergamoRoute: BergamoRoute,
  EntrarRoute: EntrarRoute,
  EquipeRoute: EquipeRoute,
  LaboratorioRoute: LaboratorioRoute,
  MembrosRoute: MembrosRouteWithChildren,
  PromptsRoute: PromptsRoute,
  CoprodutorBergamoRoute: CoprodutorBergamoRoute,
  ApiPublicDiagnosticsClientErrorRoute: ApiPublicDiagnosticsClientErrorRoute,
  ApiPublicWebhooksHotmartRoute: ApiPublicWebhooksHotmartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
