BEGIN;
SET LOCAL search_path = public, extensions;
ALTER TABLE public.admin_audit_log ADD CONSTRAINT admin_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.app_settings ADD CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.email_campaigns ADD CONSTRAINT email_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL, ADD CONSTRAINT email_campaigns_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.email_messages ADD CONSTRAINT email_messages_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.email_campaigns(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL, ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.payment_integrations ADD CONSTRAINT payment_integrations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.product_access ADD CONSTRAINT product_access_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL, ADD CONSTRAINT product_access_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE, ADD CONSTRAINT product_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.product_collaborators ADD CONSTRAINT product_collaborators_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL, ADD CONSTRAINT product_collaborators_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE, ADD CONSTRAINT product_collaborators_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.product_item_revisions ADD CONSTRAINT product_item_revisions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL, ADD CONSTRAINT product_item_revisions_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.product_items(id) ON DELETE CASCADE;
ALTER TABLE public.product_items ADD CONSTRAINT product_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL, ADD CONSTRAINT product_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE, ADD CONSTRAINT product_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.product_updates ADD CONSTRAINT product_updates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL, ADD CONSTRAINT product_updates_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.webhook_events ADD CONSTRAINT webhook_events_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.payment_integrations(id) ON DELETE CASCADE, ADD CONSTRAINT webhook_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
CREATE INDEX admin_audit_created_idx ON public.admin_audit_log (created_at DESC);
CREATE INDEX email_messages_campaign_idx ON public.email_messages (campaign_id);
CREATE INDEX leads_email_idx ON public.leads (email);
CREATE INDEX orders_email_idx ON public.orders (buyer_email);
CREATE INDEX orders_product_idx ON public.orders (product_id);
CREATE UNIQUE INDEX orders_provider_ref_unique ON public.orders (provider,provider_ref) WHERE provider IS NOT NULL AND provider_ref IS NOT NULL;
CREATE UNIQUE INDEX payment_integrations_active_unique ON public.payment_integrations (provider,external_product_ucode,external_offer_id) WHERE active;
CREATE INDEX payment_integrations_product_idx ON public.payment_integrations (product_id);
CREATE INDEX product_access_user_idx ON public.product_access (user_id);
CREATE UNIQUE INDEX product_access_user_product_unique ON public.product_access (user_id,product_id);
CREATE INDEX product_item_revisions_item_idx ON public.product_item_revisions (item_id,version DESC);
CREATE UNIQUE INDEX product_items_product_code_unique ON public.product_items (product_id,code) WHERE code IS NOT NULL;
CREATE INDEX product_items_product_id_idx ON public.product_items (product_id);
CREATE INDEX product_items_status_idx ON public.product_items (product_id,status);
CREATE INDEX product_updates_product_idx ON public.product_updates (product_id,status,published_at DESC);
CREATE UNIQUE INDEX profiles_email_normalized_unique ON public.profiles (lower(trim(email)));
CREATE UNIQUE INDEX webhook_events_idem_unique ON public.webhook_events (integration_id,external_event_id);
CREATE INDEX webhook_events_transaction_idx ON public.webhook_events (transaction_ref,event_occurred_at DESC);
COMMIT;
