BEGIN;
SET LOCAL search_path = public, extensions;
ALTER TABLE public.admin_audit_log ADD CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);
ALTER TABLE public.email_campaigns ADD CONSTRAINT email_campaigns_audience_check CHECK (audience = ANY (ARRAY['all'::text,'buyers'::text,'leads'::text,'product'::text,'manual'::text])), ADD CONSTRAINT email_campaigns_status_check CHECK (status = ANY (ARRAY['draft'::text,'sending'::text,'sent'::text,'failed'::text])), ADD CONSTRAINT email_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.email_messages ADD CONSTRAINT email_messages_status_check CHECK (status = ANY (ARRAY['queued'::text,'sent'::text,'failed'::text])), ADD CONSTRAINT email_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id), ADD CONSTRAINT email_templates_slug_key UNIQUE (slug);
ALTER TABLE public.leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id);
ALTER TABLE public.orders ADD CONSTRAINT orders_status_check CHECK (status = ANY (ARRAY['pending'::text,'paid'::text,'disputed'::text,'refunded'::text,'chargeback'::text,'canceled'::text])), ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_integrations ADD CONSTRAINT payment_integrations_environment_check CHECK (environment = ANY (ARRAY['test'::text,'production'::text])), ADD CONSTRAINT payment_integrations_provider_check CHECK (provider='hotmart'::text), ADD CONSTRAINT payment_integrations_pkey PRIMARY KEY (id);
ALTER TABLE public.product_access ADD CONSTRAINT product_access_source_check CHECK (source = ANY (ARRAY['manual'::text,'purchase'::text,'gift'::text,'trial'::text,'hotmart'::text,'manual_validation'::text,'coproducer_preview'::text])), ADD CONSTRAINT product_access_pkey PRIMARY KEY (id), ADD CONSTRAINT product_access_user_id_product_id_key UNIQUE (user_id,product_id);
ALTER TABLE public.product_collaborators ADD CONSTRAINT product_collaborators_role_check CHECK (role = ANY (ARRAY['coproducer'::text,'editor'::text,'support'::text])), ADD CONSTRAINT product_collaborators_status_check CHECK (status = ANY (ARRAY['active'::text,'revoked'::text])), ADD CONSTRAINT product_collaborators_pkey PRIMARY KEY (id), ADD CONSTRAINT product_collaborators_product_id_user_id_key UNIQUE (product_id,user_id);
ALTER TABLE public.product_item_revisions ADD CONSTRAINT product_item_revisions_pkey PRIMARY KEY (id), ADD CONSTRAINT product_item_revisions_item_id_version_key UNIQUE (item_id,version);
ALTER TABLE public.product_items ADD CONSTRAINT product_items_status_check CHECK (status = ANY (ARRAY['draft'::text,'published'::text,'archived'::text])), ADD CONSTRAINT product_items_pkey PRIMARY KEY (id);
ALTER TABLE public.product_updates ADD CONSTRAINT product_updates_status_check CHECK (status = ANY (ARRAY['draft'::text,'published'::text,'archived'::text])), ADD CONSTRAINT product_updates_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_status_check CHECK (status = ANY (ARRAY['draft'::text,'active'::text,'archived'::text])), ADD CONSTRAINT products_pkey PRIMARY KEY (id), ADD CONSTRAINT products_slug_key UNIQUE (slug);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_status_check CHECK (status = ANY (ARRAY['active'::text,'blocked'::text])), ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id), ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id,role);
ALTER TABLE public.webhook_events ADD CONSTRAINT webhook_events_processing_status_check CHECK (processing_status = ANY (ARRAY['received'::text,'processed'::text,'ignored'::text,'error'::text])), ADD CONSTRAINT webhook_events_provider_check CHECK (provider='hotmart'::text), ADD CONSTRAINT webhook_events_pkey PRIMARY KEY (id);
COMMIT;
